# Inventory\models\mappers\Inventory_Model_CellDataProvider.yml
Inventory_Model_CellDataProvider:
  type: entity
  repositoryClass: Inventory_Model_Repository_CellDataProvider
  table: Inventory_CellDataProvider

  id:
    id:
      column: id
      type: integer
      generator:
        strategy: AUTO

  fields:
    inventoryStatus:
      column: inventoryStatus
      type: string
      length: 15
      nullable: false

  oneToOne:
    orgaCell:
      targetEntity: Orga_Model_Cell
      joinColumn:
        name: idOrgaCell
        referencedColumnName: id
        nullable: false
        unique: true
    docLibraryForAFInputSetsPrimary:
      targetEntity: Doc_Model_Library
      joinColumn:
        name: idDocLibraryForAFInputSetsPrimary
        referencedColumnName: id
        nullable: true
        unique: true
      cascade: [ persist, remove ]
    aFInputSetPrimary:
      targetEntity: AF_Model_InputSet_Primary
      joinColumn:
        name: idAFInputSetPrimary
        referencedColumnName: id
        nullable: true
      cascade: [ persist, remove ]
    docBibliographyForAFInputSetPrimary:
      targetEntity: Doc_Model_Bibliography
      joinColumn:
        name: idDocBibliographyForAFInputSetPrimary
        referencedColumnName: id
        nullable: true
        unique: true
      cascade: [ persist, remove ]
    dWCube:
      targetEntity: DW_Model_Cube
      joinColumn:
        name: idDWCube
        referencedColumnName: id
        nullable: true
        unique: true
      cascade: [ persist, remove ]
    docLibraryForSocialGenericActions:
      targetEntity: Doc_Model_Library
      joinColumn:
        name: idDocLibraryForSocialGenericActions
        referencedColumnName: id
        nullable: true
        unique: true
      cascade: [ persist, remove ]
    docLibraryForSocialContextActions:
      targetEntity: Doc_Model_Library
      joinColumn:
        name: idDocLibraryForSocialContextActions
        referencedColumnName: id
        nullable: true
        unique: true
      cascade: [ persist, remove ]

  oneToMany:
    cellsGroupDataProviders:
      targetEntity: Inventory_Model_CellsGroupDataProvider
      mappedBy: containerCellDataProvider
      cascade: [ remove ]

  manyToMany:
    socialCommentsForAFInputSetPrimary:
      targetEntity: Social_Model_Comment
      joinTable:
        name: Inventory_CellDataProvider_AFInputSetPrimaryComments
        joinColumns:
          idCellDataProvider:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          idSocialComment:
            referencedColumnName: id
            nullable: false
            unique: true
      cascade: [ persist, remove ]
    socialGenericActions:
      targetEntity: Social_Model_GenericAction
      joinTable:
        name: Inventory_CellDataProvider_GenericActions
        joinColumns:
          idCellDataProvider:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          idSocialGenericAction:
            referencedColumnName: id
            nullable: false
            unique: true
      cascade: [ persist, remove ]
    socialContextActions:
      targetEntity: Social_Model_ContextAction
      joinTable:
        name: Inventory_CellDataProvider_ContextActions
        joinColumns:
          idCellDataProvider:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          idSocialContextAction:
            referencedColumnName: id
            nullable: false
            unique: true
      cascade: [ persist, remove ]
    dWResults:
      targetEntity: DW_Model_Result
      joinTable:
        name: Inventory_CellDataProvider_DWResults
        joinColumns:
          idCellDataProvider:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          idDWResult:
            referencedColumnName: id
            nullable: false
            unique: true
      cascade: [ persist, remove ]

  lifecycleCallbacks:
    postPersist: [ postSave ]
    preRemove: [ preDelete ]
