# Entrées définies dans le bootstrap:
# application.name
# application.url
# email.contact.address
# email.noreply.name
# email.noreply.address
# log.query
# feature.register

# Activation des ACL
enable.acl: true

# Logs
log.file: "data/logs/error.log"
log.query.file: "data/logs/queries.log"
Core\Log\QueryLogger:
  constructor:
    logger: log.query

# Notification des taches de fond
Core\Work\Notification\TaskNotifier:
  class: Core\Work\Notification\EmailTaskNotifier
Core\Work\Notification\EmailTaskNotifier:
  constructor:
    userService: User\Domain\UserService
    applicationName: email.noreply.name

# Délai d'attente pour les taches de fond (attend 5 secondes)
work.waitDelay: 5

# Connexion RabbitMQ
PhpAmqpLib\Connection\AMQPConnection:
  constructor:
    host: rabbitmq.host
    port: rabbitmq.port
    user: rabbitmq.user
    password: rabbitmq.password

User\Domain\UserService:
  constructor:
    applicationUrl: application.url
