# Activation des ACL
enable.acl: true

# Logs normaux
log.file: "data/logs/error.log"

# Logs des workers
worker.log.name: "log.worker"
worker.log:
  class: Monolog\Logger
  constructor:
    name: worker.log.name
  methods:
    pushHandler: worker.log.handler
worker.log.handler:
  class: Monolog\Handler\StreamHandler
  constructor:
    stream: "php://stdout"

# Définit dans le bootstrap:
# application.name:
# email.contact.address:
# email.noreply.name:
# email.noreply.address:

# Notification des taches de fond
Core\Work\Notification\TaskNotifier:
  class: Core\Work\Notification\EmailTaskNotifier
Core\Work\Notification\EmailTaskNotifier:
  constructor:
    userService: User_Service_User
    applicationName: email.noreply.name
